name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  PKG_CONFIG_PATH: C:\Mono\lib\pkgconfig
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download mono with chocolatey
      run: choco install mono -ia "INSTALLFOLDER=C:\Mono"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add readme to mods dir
      run: echo This is the directory where you put mods to be loaded by gmsl! > out/gmsl/mods/readme.txt

    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: gmsl-win64
        path: out/
