name: CMake on a single platform

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!master'

env:
  BUILD_TYPE: Release
  PKG_CONFIG_PATH: C:\Mono\lib\pkgconfig

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Cache Mono
      id: cache-mono
      uses: actions/cache@v3
      with:
        path: C:\Mono
        key: mono
        restore-keys: |
          mono

    - name: Install Mono with Chocolatey
      if: steps.cache-mono.outputs.cache-hit != 'true'
      run: choco install mono --ignore-checksums -ia "INSTALLFOLDER=C:\Mono"

    - name: Install pkgconfiglite with chocolatey
      run: choco install pkgconfiglite

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: cmd
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel %NUMBER_OF_PROCESSORS%

    - name: Add readme to mods dir
      run: echo This is the directory where you put mods to be loaded by gmsl! > out/gmsl/mods/readme.txt

    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsl-win64
        path: out/
